[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hexlet-code"
version = "0.1.5"

[tool.hatch.build.targets.wheel]
packages = ["hexlet-code"]

[project.scripts]
page-loader = "page_loader.scripts.main:main"
