[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "page_loader"
version = "0.1.4"

[tool.hatch.build.targets.wheel]
packages = ["page_loader"]

[project.scripts]
page-loader = "page_loader.scripts.main:main"
